### PR TITLE
Replaced all instances of "BoarBot" with "BoarBot: Community Edition"

### PR DESCRIPTION
**Pull request by SuperDuggy117**
yes

### CODE REVIEW

**Comment by Gcat101** [comment]
No

**Comment by Gcat101** [comment]
Don't merge it

**Comment by SuperDuggy117** [comment]
why not

**Comment by Gcat101** [comment]
You've changed some paths

**Comment by SuperDuggy117** [comment]
I was unable to commit it, so

**Comment by Gcat101** [comment]
It might break shit

**Comment by SuperDuggy117** [comment]
amazing

**Pull request closed without merging**
